version: '3.8'

services:

  scrapper_frontend:
    image: vite-docker-container
    stdin_open: true
    container_name: scrapper_frontend
    build:
      context: .
      dockerfile: ./compose/local/scrapper_frontend/Dockerfile
#    command: ./start_scrapper_frontend
    volumes:
      - "./web_grades_scrapper:/usr/src/frontend:delegated"
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true

  scrapper_backend:
    container_name: scrapper_backend
    build:
      context: .
      dockerfile: ./compose/local/scrapper_backend/Dockerfile
    command: /start_scrapper_backend
    ports:
      #HOST:CONTAINER
      - "8000:80"

