"""List metacritic types"""
SELECT_RESULT_CONTAINER = ".result"
TITLE = "product_title"
METASCORE = "metascore_w"
PLATFORM = "platform"

"""Detail metacritic types"""
SELECT_DETAIL_PLATFORMS_CONTAINER = ".product_platforms"
SELECT_DETAIL_MAIN_CONTAINER = "#main"
GENRES = "product_genre"
DEVELOPERS = "developer"
SUMMARY = "blurb_expanded"
SINGLE_PLATFORM_SUMMARY = "summary_wrap"
CRITIC_SCORE = "ratingValue"
CRITIC_BASED_ON = "count"
USER_SCORE = "user"
USER_BASED_ON = "side_details"
