services:
  production_scrapper_backend:
    container_name: production_scrapper_backend
    build:
      context: .
      dockerfile: ./compose/production/scrapper_backend/Dockerfile
    command: /start_scrapper_backend
    networks:
      - production-scrapper

networks:
  production-scrapper:
  connector:
    external: true