version: '3.3'

services:
  production_scrapper_nginx:
    image: nginx
    container_name: production_scrapper_nginx
    build:
      context: .
      dockerfile: ./compose/production/nginx/Dockerfile
    ports:
      - "80:80"
      - "443:443"
    restart: always
    volumes:
      - "./web_grades_scrapper/dist:/dist"
#      - "/app/backend/local-production-static:/app/backend/local-production-static"
    depends_on:
      - production_scrapper_backend
    networks:
      - production-scrapper

  production_scrapper_backend:
    container_name: production_scrapper_backend
    build:
      context: .
      dockerfile: ./compose/production/scrapper_backend/Dockerfile
    command: /start_scrapper_backend
    ports:
      #HOST:CONTAINER
      - "8000:80"
    networks:
      - production-scrapper

networks:
  production-scrapper: