"""List imdb types"""
LIST_CONTAINER = ".ipc-metadata-list-summary-item"
LIST_TITLE = "ipc-metadata-list-summary-item__t"
DESCRIPTION_LIST = "ipc-metadata-list-summary-item__li"
"""Detail imdb types"""
TITLE = "sc-afe43def-1"
DATA_CONTAINER = "sc-afe43def-4"
PLATFORMS = "platforms"
COMPANIES = "companies"
SCORES_CONTAINER = "app-game-scores-display"
CRITIC_DATA = "inner-orb"
IMDB_RATING_CONTAINER = "hero-rating-bar__aggregate-rating__score"
IMDB_RATING_BASED_ON = "bjjENQ"
POPULARITY = "hero-rating-bar__popularity__score"
PRESENTATION_CONTAINER = "hKIseD"
PRESENTATION_ELEMENTS = "ipc-metadata-list__item"
PRESENTATION_ELEMENTS_LABEL = "ipc-metadata-list-item__label"
NESTED_PRESENTATION_ELEMENTS = "ipc-inline-list__item"
METASCORE = "score-meta"
SCORE = "score"
PHOTOS_CONTAINER = "ipc-media ipc-media--photo"
ACTORS_CONTAINER = "kUzsHJ"
ACTOR_NAME = "fUguci"
ACTOR_CHARACTER = "llsTve"
MORE_LIKE_THIS_CONTAINER = "ipc-poster-card"
MORE_LIKE_THIS_ELEMENT_TITLE = "title"
MORE_LIKE_THIS_ELEMENT_RATING = "ipc-rating-star-group"


