"""List metacritic types"""
SELECT_CONTAINER = ".c-pageSiteSearch-results"
SELECT_RESULT_CONTAINER = "g-grid-container"
TITLE = "g-text-medium-fluid g-text-bold g-outer-spacing-bottom-small u-text-overflow-ellipsis"
METASCORE = "c-siteReviewScore_background c-siteReviewScore_background-critic_medium"
PLATFORM = "u-flexbox u-flexbox-alignCenter u-flexbox-nowrap g-gap-medium g-text-xxxsmall"

"""Detail metacritic types"""
SELECT_DETAIL_PLATFORMS_CONTAINER = ".product_platforms"
SELECT_DETAIL_MAIN_CONTAINER = ".c-pageProductGame"
DETAIL_TITLE = "c-productHero_title"
GENRES = "product_genre"
DEVELOPERS = "c-gameDetails_Developer"
SUMMARY = "c-productionDetailsGame_description"
SINGLE_PLATFORM_SUMMARY = "summary_wrap"
CRITIC_SCORE = "ratingValue"
CRITIC_BASED_ON = "count"
USER_SCORE = "user"
USER_BASED_ON = "side_details"

