"""List opencritic types"""
SELECT_RESULT_CONTAINER = "app-root"
REVIEW_CONTAINER = "app-rapid-review-list"
PLATFORMS = "platforms"
COMPANIES = "companies"
SCORES_CONTAINER = "app-game-scores-display"
CRITIC_DATA = "inner-orb"